"""
LLM Provider Live Config + Generation Integration — tests.

Coverage areas (per contract):
  A. Config — live mode enablement policy
  D. Generation integration — live mode with fake HTTP client
  E. Diagnostics API — new status fields
  F. Contract pack — new examples + validate-config endpoint
"""

from __future__ import annotations

import json
from typing import Any
from unittest.mock import MagicMock

import pytest
from fastapi.testclient import TestClient

from backend.labgen.llm_openai_compatible import (
    OpenAICompatibleLLMProviderAdapter,
    OpenAICompatibleProviderConfig,
)
from backend.labgen.llm_provider_boundary import (
    LLMProviderBoundaryService,
    LLMProviderConfig,
    LLMProviderMode,
    LLMProviderName,
    LLMProviderRequest,
)
from backend.labgen.routes import get_llm_provider_service, require_admin_user
from backend.auth_deps import get_current_user

pytestmark = pytest.mark.static

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VALID_CANDIDATE = {
    "schema_version": "1.0",
    "source_article_id": "test",
    "title": "Live LLM Test Lab",
    "description": "A test lab generated by fake-live adapter.",
    "estimated_duration_minutes": 20,
    "runtime_requirements": {"namespace_strategy": "dedicated"},
    "steps": [
        {
            "step_id": "step-1",
            "order": 1,
            "why": "Test",
            "do": "kubectl apply -f pod.yaml",
            "observe": "Pod Running",
            "explain": {"concept": "Pods", "observation": "Pod scheduled"},
        }
    ],
    "cleanup": {"namespace_cleanup": {"mode": "delete"}},
}


def _make_live_adapter(candidate: dict = None) -> OpenAICompatibleLLMProviderAdapter:
    """Build a live adapter with a fake HTTP client that returns a valid candidate."""
    mock_client = MagicMock()
    body = {
        "choices": [
            {
                "message": {"content": json.dumps(candidate or _VALID_CANDIDATE)},
                "finish_reason": "stop",
            }
        ]
    }
    mock_client.post.return_value = MagicMock(status_code=200, **{"json.return_value": body})
    return OpenAICompatibleLLMProviderAdapter(
        config=OpenAICompatibleProviderConfig(
            base_url="https://api.example.com/v1",
            model="test-model",
        ),
        api_key="sk-fake-key-for-testing-only",
        http_client=mock_client,
    )


def _make_app_with_svc(svc: LLMProviderBoundaryService, *, as_admin: bool = True):
    from contextlib import contextmanager
    from backend.main import app

    @contextmanager
    def _ctx():
        saved = dict(app.dependency_overrides)
        try:
            if as_admin:
                app.dependency_overrides[require_admin_user] = lambda: "admin"
                app.dependency_overrides[get_current_user] = lambda: "admin"
            else:
                app.dependency_overrides[get_current_user] = lambda: "student"
            app.dependency_overrides[get_llm_provider_service] = lambda: svc
            yield TestClient(app)
        finally:
            app.dependency_overrides.clear()
            app.dependency_overrides.update(saved)

    return _ctx()


# ---------------------------------------------------------------------------
# A. Config — live mode enablement
# ---------------------------------------------------------------------------


class TestLiveModeSwitching:
    def test_fake_only_is_default(self):
        svc = LLMProviderBoundaryService.create_from_env()
        assert svc.config.mode == LLMProviderMode.FAKE_ONLY
        assert svc.live_enabled is False

    def test_live_enabled_false_when_no_live_adapter(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=None,
        )
        assert svc.live_enabled is False

    def test_live_enabled_true_when_adapter_present(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        assert svc.live_enabled is True

    def test_live_enabled_returns_config_error_when_adapter_none(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=None,
        )
        req = LLMProviderRequest(
            purpose="draft_generation",
            sanitized_user_prompt="test",
        )
        resp = svc.call(req)
        assert resp.rejected_reason == "live_provider_config_error"

    def test_live_enabled_with_valid_adapter_returns_candidate(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        req = LLMProviderRequest(
            purpose="draft_generation",
            sanitized_user_prompt="deploy a pod and verify networking",
        )
        resp = svc.call(req)
        assert resp.rejected_reason is None
        assert resp.candidate_json is not None
        assert resp.candidate_json.get("title") == "Live LLM Test Lab"

    def test_safety_policy_live_enabled_when_adapter_active(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        assert svc.safety_policy.live_providers_enabled is True

    def test_safety_policy_live_disabled_when_no_adapter(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY),
        )
        assert svc.safety_policy.live_providers_enabled is False


# ---------------------------------------------------------------------------
# D. Generation integration — live mode with fake HTTP client
# ---------------------------------------------------------------------------


class TestGenerationServiceLiveMode:
    def _make_generation_service(self, live_adapter=None):
        from backend.labgen.llm_generation import (
            FakeDraftGenerationAdapter,
            LabDraftGenerationService,
        )
        from backend.labgen.repository import LabDraftRepository
        from backend.labgen.static_validator import StaticValidator

        repo = LabDraftRepository.__new__(LabDraftRepository)
        repo._path = None
        created = []

        def _create(draft):
            created.append(draft)
            return draft

        repo.create = _create
        repo.list = lambda: []

        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=live_adapter,
        )
        return LabDraftGenerationService(
            port=FakeDraftGenerationAdapter(),
            validator=StaticValidator(),
            repo=repo,
            provider_boundary=svc,
        ), created

    def test_live_mode_valid_response_creates_draft(self):
        from backend.labgen.llm_generation import LabDraftGenerationRequest

        adapter = _make_live_adapter()
        gen_svc, created = self._make_generation_service(live_adapter=adapter)
        req = LabDraftGenerationRequest(
            user_prompt="k8s networking lab",
            requester_user_id="admin",
        )
        draft, _, warnings, _ = gen_svc.generate_and_create(req)
        assert draft is not None
        assert len(created) == 1

    def test_live_mode_provider_candidate_publish_status_never_published(self):
        from backend.labgen.llm_generation import LabDraftGenerationRequest
        from backend.labgen.models import PublishStatus

        adapter = _make_live_adapter(
            candidate={**_VALID_CANDIDATE, "publish_status": "published"}
        )
        gen_svc, created = self._make_generation_service(live_adapter=adapter)
        req = LabDraftGenerationRequest(
            user_prompt="k8s lab",
            requester_user_id="admin",
        )
        draft, _, _, _ = gen_svc.generate_and_create(req)
        assert draft.publish_status != PublishStatus.PUBLISHED

    def test_live_mode_provider_failure_does_not_create_draft(self):
        from backend.labgen.llm_generation import (
            DraftGenerationRejected,
            LabDraftGenerationRequest,
        )

        # Adapter with no live_adapter → config_error → rejected_reason
        gen_svc, created = self._make_generation_service(live_adapter=None)
        req = LabDraftGenerationRequest(
            user_prompt="k8s lab",
            requester_user_id="admin",
        )
        with pytest.raises(DraftGenerationRejected):
            gen_svc.generate_and_create(req)
        assert len(created) == 0

    def test_default_fake_path_unchanged_when_no_live_adapter(self):
        from backend.labgen.llm_generation import (
            FakeDraftGenerationAdapter,
            LabDraftGenerationRequest,
            LabDraftGenerationService,
        )
        from backend.labgen.repository import LabDraftRepository
        from backend.labgen.static_validator import StaticValidator

        repo = LabDraftRepository.__new__(LabDraftRepository)
        repo._path = None
        created = []
        repo.create = lambda d: created.append(d) or d
        repo.list = lambda: []

        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY),
        )
        gen_svc = LabDraftGenerationService(
            port=FakeDraftGenerationAdapter(),
            validator=StaticValidator(),
            repo=repo,
            provider_boundary=svc,
        )
        req = LabDraftGenerationRequest(
            user_prompt="regression test",
            requester_user_id="admin",
        )
        draft, _, _, _ = gen_svc.generate_and_create(req)
        assert draft is not None


# ---------------------------------------------------------------------------
# E. Diagnostics API — new status fields
# ---------------------------------------------------------------------------


class TestProviderStatusExtendedFields:
    def test_status_returns_generation_supported(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY)
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert "generation_supported" in body

    def test_status_returns_repair_supported_false(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY)
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert body["repair_supported"] is False

    def test_status_live_enabled_false_for_fake_only(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY)
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert body["live_enabled"] is False

    def test_status_live_enabled_true_for_live_mode_with_adapter(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert body["live_enabled"] is True

    def test_status_config_issues_empty_for_fake_only(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY)
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert "config_issues" in body
        assert isinstance(body["config_issues"], list)

    def test_status_shows_configured_model_when_live(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        assert body["configured_model"] == "test-model"

    def test_status_shows_base_url_origin_not_full_path(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        body = r.json()
        # origin = scheme + host only, no path
        origin = body.get("base_url_origin", "")
        assert "https://api.example.com" == origin

    def test_status_never_contains_api_key(self):
        adapter = _make_live_adapter()
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.LIVE_ENABLED),
            live_adapter=adapter,
        )
        with _make_app_with_svc(svc) as client:
            r = client.get("/api/labgen/llm-provider/status")
        assert "sk-fake" not in r.text
        assert "fake-key" not in r.text

    def test_non_admin_forbidden(self):
        svc = LLMProviderBoundaryService(
            config=LLMProviderConfig(mode=LLMProviderMode.FAKE_ONLY)
        )
        with _make_app_with_svc(svc, as_admin=False) as client:
            r = client.get("/api/labgen/llm-provider/status")
        assert r.status_code == 403


class TestValidateConfigEndpoint:
    def _client(self):
        from contextlib import contextmanager
        from backend.main import app

        @contextmanager
        def _ctx():
            saved = dict(app.dependency_overrides)
            try:
                app.dependency_overrides[require_admin_user] = lambda: "admin"
                app.dependency_overrides[get_current_user] = lambda: "admin"
                yield TestClient(app)
            finally:
                app.dependency_overrides.clear()
                app.dependency_overrides.update(saved)

        return _ctx()

    def test_admin_can_validate(self):
        with self._client() as client:
            r = client.post("/api/labgen/llm-provider/validate-config")
        assert r.status_code == 200

    def test_non_admin_forbidden(self):
        from backend.main import app
        saved = dict(app.dependency_overrides)
        try:
            app.dependency_overrides[get_current_user] = lambda: "student"
            client = TestClient(app)
            r = client.post("/api/labgen/llm-provider/validate-config")
        finally:
            app.dependency_overrides.clear()
            app.dependency_overrides.update(saved)
        assert r.status_code == 403

    def test_response_has_valid_and_config_issues(self):
        with self._client() as client:
            r = client.post("/api/labgen/llm-provider/validate-config")
        body = r.json()
        assert "valid" in body
        assert "config_issues" in body

    def test_response_never_contains_api_key(self):
        with self._client() as client:
            r = client.post("/api/labgen/llm-provider/validate-config")
        assert "sk-" not in r.text
        assert "api_key" not in r.text.lower() or '"api_key"' not in r.text


# ---------------------------------------------------------------------------
# F. Contract pack — new endpoints and examples
# ---------------------------------------------------------------------------


class TestContractPackLiveProviderUpdates:
    def _admin_client(self):
        from contextlib import contextmanager
        from backend.main import app

        @contextmanager
        def _ctx():
            saved = dict(app.dependency_overrides)
            try:
                app.dependency_overrides[require_admin_user] = lambda: "admin"
                app.dependency_overrides[get_current_user] = lambda: "admin"
                yield TestClient(app)
            finally:
                app.dependency_overrides.clear()
                app.dependency_overrides.update(saved)

        return _ctx()

    def test_validate_config_endpoint_in_contract(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        paths = [e["path"] for e in r.json()["endpoints"]]
        assert "/api/labgen/llm-provider/validate-config" in paths

    def test_llm_provider_status_live_example_in_contract(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        names = [e["name"] for e in r.json()["example_responses"]]
        assert "llm_provider_status_live_enabled" in names

    def test_validate_config_example_in_contract(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        names = [e["name"] for e in r.json()["example_responses"]]
        assert "llm_provider_validate_config_invalid" in names

    def test_sensitive_policy_includes_authorization(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        prohibited = r.json()["sensitive_field_policy"]["prohibited_in_response_values"]
        assert "authorization" in prohibited or "authorization_header" in prohibited

    def test_contract_examples_no_api_keys(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        body = r.json()
        text = json.dumps(body)
        assert "sk-" not in text
        assert "Bearer " not in text

    def test_provider_status_example_has_live_enabled_false(self):
        with self._admin_client() as client:
            r = client.get("/api/labgen/contract-pack")
        examples = {e["name"]: e for e in r.json()["example_responses"]}
        status_example = examples.get("llm_provider_status", {})
        resp = status_example.get("response", {})
        assert resp.get("live_enabled") is False
